global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
      - 10.0.1.5:9090

  - job_name: 'pleroma'
    metrics_path: /api/pleroma/app_metrics
    scheme: https
    static_configs:
    - targets: 
      - pl-local.rokoucha.net:50443

  - job_name: 'postgres'
    static_configs:
    - targets: 
      - 10.0.1.5:9187

  - job_name: 'coreos'
    static_configs:
    - targets:
      - 10.0.1.5:9100