global:
  scrape_interval: 15s
  evaluation_interval: 30s

remote_write:
  - url: http://host.containers.internal:19291

scrape_configs:
  # tomoko prometheus
  - job_name: prometheus
    static_configs:
      - targets:
          - host.containers.internal:9090
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # tomoko postgresql-exporter
  - job_name: "postgres"
    static_configs:
      - targets:
          - host.containers.internal:9187
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # tomoko nginx-prometheus-exporter
  - job_name: "nginx"
    static_configs:
      - targets:
          - host.containers.internal:9113
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # tomoko node_exporter
  - job_name: "tomoko"
    static_configs:
      - targets:
          - host.containers.internal:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # shizuka node_exporter
  - job_name: "shizuka"
    static_configs:
      - targets:
          - 172.16.2.12:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "shizuka"

  # adolfine vmware_exporter
  - job_name: "adolfine"
    static_configs:
      - targets:
          - host.containers.internal:9272
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "adolfine"

  # haruka node_exporter
  - job_name: "haruka"
    static_configs:
      - targets:
          - 172.16.2.21:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "haruka"

  # haruka mirakurun-exporter
  - job_name: "mirakurun"
    scrape_interval: 60s
    static_configs:
      - targets:
          - 172.16.2.21:9684
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "mirakurun"

  # haruka intel-prometheus
  - job_name: "intel-igpu"
    scrape_interval: 60s
    static_configs:
      - targets:
          - 172.16.2.21:8080
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "intel-igpu"

  # IX2207 snmp_expoter if_mib
  - job_name: "ix2207-if_mib"
    static_configs:
      - targets:
          - 172.16.2.1
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.containers.internal:9116

  # IX2207 snmp_expoter nec_ix
  - job_name: "ix2207-nec_ix"
    static_configs:
      - targets:
          - 172.16.2.1
    metrics_path: /snmp
    params:
      module: [nec_ix]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.containers.internal:9116

  # tomoko apcupsd_exporter
  - job_name: "apcupsd"
    scrape_interval: 60s
    static_configs:
      - targets:
          - host.containers.internal:59162
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "apcupsd"

  # tomoko switchbot-meter-expoter
  - job_name: "switchbot-meter"
    scrape_interval: 1m
    metrics_path: /probe
    static_configs:
      - targets:
          - CED37C9CA281
          - D4DF46B693B1
          - ED867D5919E9
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.containers.internal:8888

  # tomoko statsd_exporter
  - job_name: statsd
    static_configs:
      - targets:
          - host.containers.internal:9102

  # tomoko elasticsearch_expoter
  - job_name: elasticsearch
    scrape_interval: 1m
    static_configs:
      - targets:
          - host.containers.internal:9114

  # elma node_exporter
  - job_name: elma
    static_configs:
      - targets:
          - 172.16.2.14:9100
    relabel_configs:
      - target_label: instance
        replacement: "elma"

  # elma blackbox_exporter
  - job_name: "blackbox_exporter"
    scrape_interval: 1m
    static_configs:
      - targets: [172.16.2.14:9115]
    relabel_configs:
      - target_label: instance
        replacement: "elma"

  # elma blackbox_exporter bbix-4over6-v4
  - job_name: "bbix-4over6-v4"
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [ping_bbix-4over6-v4]
    static_configs:
      - targets:
          - 172.16.10.1
          - 1.1.1.1
          - 8.8.8.8
          - ping-e.sinet.ad.jp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.2.14:9115

  # elma blackbox_exporter bbix-pppoe-v4
  - job_name: "bbix-pppoe-v4"
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [ping_bbix-pppoe-v4]
    static_configs:
      - targets:
          - 172.16.11.1
          - 1.1.1.1
          - 8.8.8.8
          - ping-e.sinet.ad.jp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.2.14:9115

  # elma blackbox_exporter mobile-v4
  - job_name: "mobile-v4"
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [ping_mobile-v4]
    static_configs:
      - targets:
          - 172.16.12.1
          - 1.1.1.1
          - 8.8.8.8
          - ping-e.sinet.ad.jp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.2.14:9115

  # vesna blackbox_exporter itscom-v4
  - job_name: "itscom-v4"
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [ping_itscom-v4]
    static_configs:
      - targets:
          - 172.16.13.1
          - 1.1.1.1
          - 8.8.8.8
          - ping-e.sinet.ad.jp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.2.14:9115

  # tomoko cadvisor
  - job_name: cadvisor
    static_configs:
      - targets:
          - host.containers.internal:48080

  # tomoko mariadb-exporter
  - job_name: mariadb
    static_configs:
      - targets:
          - host.containers.internal:9104

  # tomoko podman-exporter
  - job_name: podman
    static_configs:
      - targets:
          - host.containers.internal:9882
