global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  # self monitoring
  - job_name: "prometheus"
    static_configs:
      - targets:
          - 172.16.2.11:9090
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # Pleroma/Rokoucha
  - job_name: "pleroma"
    metrics_path: /api/pleroma/app_metrics
    scheme: https
    static_configs:
      - targets:
          - pl-local.rokoucha.net:50443
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # PostgreSQL
  - job_name: "postgres"
    static_configs:
      - targets:
          - 172.16.2.11:9187
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # Nginx
  - job_name: "nginx"
    static_configs:
      - targets:
          - 172.16.2.11:9113
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # tomoko node_exporter
  - job_name: "tomoko"
    static_configs:
      - targets:
          - 172.16.2.11:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "tomoko"

  # shizuka node_exporter
  - job_name: "shizuka"
    static_configs:
      - targets:
          - 172.16.2.12:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "shizuka"

  # adolfine vmware_exporter
  - job_name: "adolfine"
    static_configs:
      - targets:
          - 172.16.2.11:9272
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "adolfine"

  # haruka node_exporter
  - job_name: "haruka"
    static_configs:
      - targets:
          - 172.16.2.21:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "haruka"

  # haruka mirakurun-exporter
  - job_name: "mirakurun"
    scrape_interval: 60s
    static_configs:
      - targets:
          - 172.16.2.21:9684
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "mirakurun"

  # haruka intel-prometheus
  - job_name: "intel-igpu"
    scrape_interval: 60s
    static_configs:
      - targets:
          - 172.16.2.21:8080
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "intel-igpu"

  # IX2207 snmp_expoter if_mib
  - job_name: "ix2207-if_mib"
    static_configs:
      - targets:
          - 172.16.2.1
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.2.11:9116

  # IX2207 snmp_expoter nec_ix
  - job_name: "ix2207-nec_ix"
    static_configs:
      - targets:
          - 172.16.2.1
    metrics_path: /snmp
    params:
      module: [nec_ix]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.2.11:9116

  # tomoko apcupsd_exporter
  - job_name: "apcupsd"
    scrape_interval: 60s
    static_configs:
      - targets:
          - 172.16.2.11:59162
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "apcupsd"
